
#define OK 1
#define LOGIN_SUCCESSFUL 2
#define USERNAME_REGISTERED 3
#define REGISTRATION_SUCCESSFUL 4


#define ERROR -1
#define LOGIN_FAILED -2
#define USERNAME_NOT_REGISTERED -3
#define REGISTRATION_FAILED -4
#define HONEYPOT_HIT -5
#define HONEYWORD_HIT -6
#define WRONG_PASSWORD -7



